const colors = {
	PRIMARY: '#78A6FF',
	SECONDARY: '#FD739C',
	HEADING: '#07092F',
	TEXT: '#424360',
	LIGHT_TEXT: '#7C7D8F',
	PLACEHOLDER: '#ACACBE',
	INPUT_BORDER: '#DEDFE8',
	BORDER: '#F2F3FA',
	LIGHT_BLUEISH_GRAY: '#FAFBFF',
	LIGHT_GRAY: '#f9f9f9',
	DISABLED: '#BFBFBF',
	WHITE: '#FFFFFF',
	ALERT_BORDER: '#FFA8A8',
	ALERT: '#ff8787',
	SHADOW: '#EFF0F6',
};

export default colors;
