name: Deploy to staging server

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use PHP7
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install javascript dependencies
        run: yarn install

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install php dependencies
        run: composer install --optimize-autoloader

      - name: Checking code and formattings
        run: |
          yarn lint
          yarn prettier

      - name: Build the application
        run: |
          yarn build
          yarn release

      - name: Deploy to staging server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          ssh_private_key: ${{ secrets.STAGING_PRIVATE_KEY }}
          local_path: './release/*.zip'
          remote_path: 'public_html/'
          args: '-o ConnectTimeout=10'

      - name: Install the plugin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          script: |
            rm -rf ~/public_html/wp-content/plugins/wordpress-lms
            rm -rf ~/public_html/wp-content/plugins/learning-management-system
            cd public_html
            wp plugin install learning-management-system.zip --force --activate
